name: deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name  'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -yy pandoc
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install reapack-index
        run: gem install reapack-index --pre
      - name: Update index.xml
        run: reapack-index --commit
      - name: Push changes
        run: git push
